### PR TITLE
fix: agent-sdk missing storage type

### PR DESCRIPTION
**Pull request by DRK3**
Hardcoded to IndexedDB for now. In the future this will be customizable.

Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

### CODE REVIEW

**Review by fqutishat — APPROVED** [review]

**Review by rolsonquadras — APPROVED** [review]

**Review by sudeshrshetty — COMMENTED** [review]
Where is ENV variable to be passed through docker?

**Comment by DRK3** [comment]
@sudeshrshetty This will be added later. This change I made allows the edge-agent to use agent-sdk like it did before without worrying about the new EDV stuff, which isn't ready for full usage yet.

**Comment by sudeshrshetty** [comment]
> @sudeshrshetty This will be added later. This change I made allows the edge-agent to use agent-sdk like it did before without worrying about the new EDV stuff, which isn't ready for full usage yet.

Create an issue and add a TODO

**Review by sudeshrshetty — APPROVED** [review]

**Comment by DRK3** [comment]
> > @sudeshrshetty This will be added later. This change I made allows the edge-agent to use agent-sdk like it did before without worrying about the new EDV stuff, which isn't ready for full usage yet.
> 
> Create an issue and add a TODO

Done!

**Pull request merged**
